### PR TITLE
Fix dragbar bugs & other minor changes

### PR DESCRIPTION
**Pull request by Damian-11**
- Fix the dragbar not being in the correct position after the main UI is unhidden
image
- Fix cursor becoming a hand/pointer when hovering over hidden dragbar
image
- Add more alternative HTTP request functions for different executors
- Fix incorrect escape sequence in getIcon function

### CODE REVIEW

**Comment by Damian-11** [comment]
Ping @shlexware

**Comment by shlexware** [comment]
I'm pretty sure we fixed the issue with the dragbar positioning and hover icon. 
Could you confirm if this is still happening now?

**Comment by Damian-11** [comment]
> I'm pretty sure we fixed the issue with the dragbar positioning and hover icon. 
> Could you confirm if this is still happening now?

I'm not able to test it myself as I'm currently away from home (and will be for a while). I skimmed over the source code and did not see any fixes for the aforementioned issues. A proper fix would require the following:

1. Resetting the dragbar's position when the window is unhidden. This is required because unhiding the window also resets its position to the center of the screen. Currently, the dragbar only updates its position while it is actively being dragged. This results in it staying behind at the old position until you start dragging it (as shown in my first picture).

2. Setting the dragbar element's `Visible` property to false when the window is hidden to prevent the hover icon.

You can always use an emulator and test it yourself if you're still unsure. I personally recommend either LD player or BlueStacks.

**Comment by Damian-11** [comment]
> merge issues- ported your changes over in some form in 1.55 :)
> thanks!!

Thank you, that'll work. Although I believe that resolving the conflicts manually and then merging would work better. 😁

**Pull request closed without merging**
